2023-08-18 11:20:41,864 INFO    MainThread:48238 [internal.py:wandb_internal():90] W&B internal server running at pid: 48238, started at: 2023-08-18 11:20:41.864752
2023-08-18 11:20:41,866 DEBUG   HandlerThread:48238 [handler.py:handle_request():141] handle_request: run_start
2023-08-18 11:20:41,867 INFO    WriterThread:48238 [datastore.py:open_for_write():75] open: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230818_112041-3bdhb0od/run-3bdhb0od.wandb
2023-08-18 11:20:41,867 DEBUG   HandlerThread:48238 [meta.py:__init__():35] meta init
2023-08-18 11:20:41,868 DEBUG   HandlerThread:48238 [meta.py:__init__():49] meta init done
2023-08-18 11:20:41,868 DEBUG   HandlerThread:48238 [meta.py:probe():209] probe
2023-08-18 11:20:41,869 DEBUG   HandlerThread:48238 [meta.py:_setup_git():199] setup git
2023-08-18 11:20:41,876 DEBUG   HandlerThread:48238 [meta.py:_setup_git():206] setup git done
2023-08-18 11:20:41,877 DEBUG   HandlerThread:48238 [meta.py:_save_pip():53] save pip
2023-08-18 11:20:41,877 DEBUG   HandlerThread:48238 [meta.py:_save_pip():67] save pip done
2023-08-18 11:20:41,877 DEBUG   HandlerThread:48238 [meta.py:probe():247] probe done
2023-08-18 11:20:44,440 WARNING MainThread:48238 [internal.py:wandb_internal():153] Internal process interrupt: 1
2023-08-18 11:20:44,697 WARNING MainThread:48238 [internal.py:wandb_internal():153] Internal process interrupt: 2
2023-08-18 11:20:44,697 ERROR   MainThread:48238 [internal.py:wandb_internal():156] Internal process interrupted.
2023-08-18 11:20:44,870 INFO    SenderThread:48238 [sender.py:finish():1111] shutting down sender
2023-08-18 11:20:45,442 INFO    WriterThread:48238 [datastore.py:close():279] close: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230818_112041-3bdhb0od/run-3bdhb0od.wandb
2023-08-18 11:20:45,443 INFO    HandlerThread:48238 [handler.py:finish():806] shutting down handler
2023-08-18 11:20:45,445 INFO    MainThread:48238 [internal.py:handle_exit():80] Internal process exited
