2023-07-20 15:49:40,864 INFO    MainThread:13311 [internal.py:wandb_internal():90] W&B internal server running at pid: 13311, started at: 2023-07-20 15:49:40.864454
2023-07-20 15:49:40,866 DEBUG   HandlerThread:13311 [handler.py:handle_request():141] handle_request: run_start
2023-07-20 15:49:40,866 INFO    WriterThread:13311 [datastore.py:open_for_write():75] open: /home/nicole/marl-emecom/src/experiments_pgg_v0/anastassacos/wandb/offline-run-20230720_154940-uxw33ep5/run-uxw33ep5.wandb
2023-07-20 15:49:40,868 DEBUG   HandlerThread:13311 [meta.py:__init__():35] meta init
2023-07-20 15:49:40,868 DEBUG   HandlerThread:13311 [meta.py:__init__():49] meta init done
2023-07-20 15:49:40,868 DEBUG   HandlerThread:13311 [meta.py:probe():209] probe
2023-07-20 15:49:40,869 DEBUG   HandlerThread:13311 [meta.py:_setup_git():199] setup git
2023-07-20 15:49:40,877 DEBUG   HandlerThread:13311 [meta.py:_setup_git():206] setup git done
2023-07-20 15:49:40,877 DEBUG   HandlerThread:13311 [meta.py:_save_pip():53] save pip
2023-07-20 15:49:40,877 DEBUG   HandlerThread:13311 [meta.py:_save_pip():67] save pip done
2023-07-20 15:49:40,877 DEBUG   HandlerThread:13311 [meta.py:probe():247] probe done
2023-07-20 15:49:45,225 WARNING MainThread:13311 [internal.py:wandb_internal():153] Internal process interrupt: 1
2023-07-20 15:49:45,727 WARNING MainThread:13311 [internal.py:wandb_internal():153] Internal process interrupt: 2
2023-07-20 15:49:45,727 ERROR   MainThread:13311 [internal.py:wandb_internal():156] Internal process interrupted.
2023-07-20 15:49:45,868 INFO    SenderThread:13311 [sender.py:finish():1111] shutting down sender
2023-07-20 15:49:46,227 INFO    WriterThread:13311 [datastore.py:close():279] close: /home/nicole/marl-emecom/src/experiments_pgg_v0/anastassacos/wandb/offline-run-20230720_154940-uxw33ep5/run-uxw33ep5.wandb
2023-07-20 15:49:46,227 INFO    HandlerThread:13311 [handler.py:finish():806] shutting down handler
2023-07-20 15:49:46,228 INFO    MainThread:13311 [internal.py:handle_exit():80] Internal process exited
