2023-08-18 11:09:42,500 INFO    MainThread:47762 [internal.py:wandb_internal():90] W&B internal server running at pid: 47762, started at: 2023-08-18 11:09:42.499902
2023-08-18 11:09:42,502 DEBUG   HandlerThread:47762 [handler.py:handle_request():141] handle_request: run_start
2023-08-18 11:09:42,502 INFO    WriterThread:47762 [datastore.py:open_for_write():75] open: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230818_110942-mid0jj8x/run-mid0jj8x.wandb
2023-08-18 11:09:42,503 DEBUG   HandlerThread:47762 [meta.py:__init__():35] meta init
2023-08-18 11:09:42,503 DEBUG   HandlerThread:47762 [meta.py:__init__():49] meta init done
2023-08-18 11:09:42,503 DEBUG   HandlerThread:47762 [meta.py:probe():209] probe
2023-08-18 11:09:42,504 DEBUG   HandlerThread:47762 [meta.py:_setup_git():199] setup git
2023-08-18 11:09:42,511 DEBUG   HandlerThread:47762 [meta.py:_setup_git():206] setup git done
2023-08-18 11:09:42,511 DEBUG   HandlerThread:47762 [meta.py:_save_pip():53] save pip
2023-08-18 11:09:42,512 DEBUG   HandlerThread:47762 [meta.py:_save_pip():67] save pip done
2023-08-18 11:09:42,512 DEBUG   HandlerThread:47762 [meta.py:probe():247] probe done
2023-08-18 11:10:37,774 WARNING MainThread:47762 [internal.py:wandb_internal():153] Internal process interrupt: 1
2023-08-18 11:10:37,951 WARNING MainThread:47762 [internal.py:wandb_internal():153] Internal process interrupt: 2
2023-08-18 11:10:37,951 ERROR   MainThread:47762 [internal.py:wandb_internal():156] Internal process interrupted.
2023-08-18 11:10:38,509 INFO    SenderThread:47762 [sender.py:finish():1111] shutting down sender
2023-08-18 11:10:38,784 INFO    WriterThread:47762 [datastore.py:close():279] close: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230818_110942-mid0jj8x/run-mid0jj8x.wandb
2023-08-18 11:10:38,785 INFO    HandlerThread:47762 [handler.py:finish():806] shutting down handler
2023-08-18 11:10:38,786 INFO    MainThread:47762 [internal.py:handle_exit():80] Internal process exited
