2023-07-21 10:30:33,425 INFO    MainThread:28565 [internal.py:wandb_internal():90] W&B internal server running at pid: 28565, started at: 2023-07-21 10:30:33.425215
2023-07-21 10:30:33,427 DEBUG   HandlerThread:28565 [handler.py:handle_request():141] handle_request: run_start
2023-07-21 10:30:33,428 INFO    WriterThread:28565 [datastore.py:open_for_write():75] open: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230721_103033-x89uva3s/run-x89uva3s.wandb
2023-07-21 10:30:33,428 DEBUG   HandlerThread:28565 [meta.py:__init__():35] meta init
2023-07-21 10:30:33,428 DEBUG   HandlerThread:28565 [meta.py:__init__():49] meta init done
2023-07-21 10:30:33,428 DEBUG   HandlerThread:28565 [meta.py:probe():209] probe
2023-07-21 10:30:33,429 DEBUG   HandlerThread:28565 [meta.py:_setup_git():199] setup git
2023-07-21 10:30:33,437 DEBUG   HandlerThread:28565 [meta.py:_setup_git():206] setup git done
2023-07-21 10:30:33,437 DEBUG   HandlerThread:28565 [meta.py:_save_pip():53] save pip
2023-07-21 10:30:33,437 DEBUG   HandlerThread:28565 [meta.py:_save_pip():67] save pip done
2023-07-21 10:30:33,437 DEBUG   HandlerThread:28565 [meta.py:probe():247] probe done
2023-07-21 10:30:35,974 WARNING MainThread:28565 [internal.py:wandb_internal():153] Internal process interrupt: 1
2023-07-21 10:30:36,158 WARNING MainThread:28565 [internal.py:wandb_internal():153] Internal process interrupt: 2
2023-07-21 10:30:36,158 ERROR   MainThread:28565 [internal.py:wandb_internal():156] Internal process interrupted.
2023-07-21 10:30:36,428 INFO    SenderThread:28565 [sender.py:finish():1111] shutting down sender
2023-07-21 10:30:37,041 INFO    WriterThread:28565 [datastore.py:close():279] close: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230721_103033-x89uva3s/run-x89uva3s.wandb
2023-07-21 10:30:37,041 INFO    HandlerThread:28565 [handler.py:finish():806] shutting down handler
2023-07-21 10:30:37,043 INFO    MainThread:28565 [internal.py:handle_exit():80] Internal process exited
